import type { CompiledProc, ProcOp } from '../engine/types.js';

/** Generated by `npm run build` — do not edit by hand. */
const SERIALIZED = [
  {
    "ruleId": 706872253,
    "hosts": [
      "generic-ecommerce.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": ".urgency-banner",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "only \\d+ left in stock",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "ruleId": 3155015987,
    "hosts": [
      "sneaky-news.example.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "button",
    "procedural": [
      {
        "type": "has-text",
        "needle": "I hate saving money"
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "ruleId": 2386664191,
    "hosts": [
      "sketchy-airlines.example.com"
    ],
    "entity": false,
    "pathRe": {
      "source": "^\\/checkout\\/.*.*",
      "flags": ""
    },
    "selector": "input[name=\"travel_insurance\"]",
    "procedural": [],
    "action": {
      "type": "uncheck"
    }
  },
  {
    "ruleId": 2746467523,
    "hosts": [
      "consent.example.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "input[name=\"marketing_opt_in\"]",
    "procedural": [],
    "action": {
      "type": "uncheck"
    }
  },
  {
    "ruleId": 3770666557,
    "hosts": [
      "read-it-all.example.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": ".signup-wall-close",
    "procedural": [],
    "action": {
      "type": "click-dismiss"
    }
  },
  {
    "ruleId": 2217337770,
    "hosts": [
      "read-it-all.example.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "body",
    "procedural": [],
    "action": {
      "type": "unlock-scroll"
    }
  },
  {
    "ruleId": 2282359013,
    "hosts": [
      "amazon.in",
      "www.amazon.in"
    ],
    "entity": false,
    "pathRe": null,
    "selector": ".a-carousel-card",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "cashback",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "ruleId": 3499420505,
    "hosts": [
      "amazon.in",
      "www.amazon.in"
    ],
    "entity": false,
    "pathRe": null,
    "selector": ".a-carousel-card",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "orders above",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "ruleId": 2587038438,
    "hosts": [
      "amazon.in",
      "www.amazon.in"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "a[href*=\"/alm/storefront\"]",
    "procedural": [
      {
        "type": "upward",
        "steps": ".a-carousel-card"
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "ruleId": 2023833575,
    "hosts": [
      "amazon-en"
    ],
    "entity": false,
    "pathRe": null,
    "selector": ".a-badge",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "limited time deal",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "ruleId": 4135333337,
    "hosts": [
      "amazon-en"
    ],
    "entity": false,
    "pathRe": null,
    "selector": ".a-badge",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "ends in",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "ruleId": 1766186056,
    "hosts": [
      "www.flipkart.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "div.HZ0E6r.Rm9_cy",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "^Only (few|\\d+ left)",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "ruleId": 912433863,
    "hosts": [
      "mloshoes.com",
      "www.mloshoes.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": ".announcement__slide",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "ends in",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "ruleId": 2945835325,
    "hosts": [
      "mloshoes.com",
      "www.mloshoes.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": ".badge-box.custom-box",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "best seller",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  }
] as const;

interface SerializedRegex {
  source: string;
  flags: string;
}

type SerializedProcOp =
  | { type: 'has-text'; needle: string | SerializedRegex }
  | { type: 'matches-path'; pattern: string | SerializedRegex }
  | { type: 'matches-attr'; name: string; value?: string | SerializedRegex }
  | { type: 'matches-css'; property: string; value: string | SerializedRegex }
  | { type: 'upward'; steps: number | string }
  | { type: 'watch-attr'; names: string[] }
  | { type: 'min-text-length'; length: number };

type SerializedAction =
  | { type: 'hide' }
  | { type: 'uncheck' }
  | { type: 'click-dismiss' }
  | { type: 'unlock-scroll' }
  | { type: 'remove' }
  | { type: 'remove-attr'; pattern: string | SerializedRegex }
  | { type: 'remove-class'; pattern: string | SerializedRegex }
  | { type: 'style'; decls: Array<[string, string]> };

interface SerializedRule {
  ruleId: number;
  hosts: string[];
  entity: boolean;
  pathRe: SerializedRegex | null;
  selector: string;
  procedural: SerializedProcOp[];
  action: SerializedAction;
}

function reviveRegex(value: string | SerializedRegex): string | RegExp {
  if (typeof value === 'string') {
    return value;
  }
  return new RegExp(value.source, value.flags);
}

function reviveProcOp(op: SerializedProcOp): ProcOp {
  switch (op.type) {
    case 'has-text':
      return { type: 'has-text', needle: reviveRegex(op.needle) };
    case 'matches-path':
      return { type: 'matches-path', pattern: reviveRegex(op.pattern) };
    case 'matches-attr':
      return {
        type: 'matches-attr',
        name: op.name,
        value: op.value === undefined ? undefined : reviveRegex(op.value),
      };
    case 'matches-css':
      return {
        type: 'matches-css',
        property: op.property,
        value: reviveRegex(op.value),
      };
    case 'upward':
      return { type: 'upward', steps: op.steps };
    case 'watch-attr':
      return { type: 'watch-attr', names: op.names };
    case 'min-text-length':
      return { type: 'min-text-length', length: op.length };
    default:
      return { type: 'watch-attr', names: [] };
  }
}

function reviveAction(action: SerializedAction): CompiledProc['action'] {
  switch (action.type) {
    case 'remove-attr':
      return { type: 'remove-attr', pattern: reviveRegex(action.pattern) };
    case 'remove-class':
      return { type: 'remove-class', pattern: reviveRegex(action.pattern) };
    default:
      return action;
  }
}

export function revivePackagedRules(): CompiledProc[] {
  return (SERIALIZED as SerializedRule[]).map((row) => ({
    ruleId: row.ruleId,
    hosts: row.hosts,
    entity: row.entity,
    pathRe: row.pathRe ? new RegExp(row.pathRe.source, row.pathRe.flags) : null,
    selector: row.selector,
    procedural: row.procedural.map(reviveProcOp),
    action: reviveAction(row.action),
  }));
}
