import type { CompiledProc } from '../engine/types.js';
import { reviveCompiledProc, type StoredCompiledProc } from '../engine/serialized.js';

/** Generated by `npm run build` — do not edit by hand. */
export const PACKAGED_REV = 202610012315;

export type PackagedList = 'darklist' | 'e2e-fixture' | 'third-party';

export interface PackagedRule {
  rule: CompiledProc;
  list: PackagedList;
}

const SERIALIZED = [
  {
    "list": "darklist",
    "ruleId": 706872253,
    "hosts": [
      "generic-ecommerce.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": ".urgency-banner",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "only \\d+ left in stock",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 3155015987,
    "hosts": [
      "sneaky-news.example.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "button",
    "procedural": [
      {
        "type": "has-text",
        "needle": "I hate saving money"
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 2386664191,
    "hosts": [
      "sketchy-airlines.example.com"
    ],
    "entity": false,
    "pathRe": {
      "source": "^\\/checkout\\/.*.*",
      "flags": ""
    },
    "selector": "input[name=\"travel_insurance\"]",
    "procedural": [],
    "action": {
      "type": "uncheck"
    }
  },
  {
    "list": "darklist",
    "ruleId": 2746467523,
    "hosts": [
      "consent.example.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "input[name=\"marketing_opt_in\"]",
    "procedural": [],
    "action": {
      "type": "uncheck"
    }
  },
  {
    "list": "darklist",
    "ruleId": 3770666557,
    "hosts": [
      "read-it-all.example.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": ".signup-wall-close",
    "procedural": [],
    "action": {
      "type": "click-dismiss"
    }
  },
  {
    "list": "darklist",
    "ruleId": 2217337770,
    "hosts": [
      "read-it-all.example.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "body",
    "procedural": [],
    "action": {
      "type": "unlock-scroll"
    }
  },
  {
    "list": "darklist",
    "ruleId": 301169397,
    "hosts": [
      "www.getyourguide.com"
    ],
    "entity": false,
    "pathRe": {
      "source": "^\\/(?:[a-z]{2}(?:-[a-z]{2})?\\/)?(?:cart\\/?|(?:[^/?]+-l\\d+(?:\\/[^/?]+-t\\d+)?\\/?)?)(?:\\?.*)?$",
      "flags": ""
    },
    "selector": "span[id$=\"-likelyToSellOut-badge\"]:not(:has(button, a, input, select, textarea, [role=\"button\"]))",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "^Likely to sell out$",
          "flags": ""
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 416051888,
    "hosts": [
      "www.getyourguide.com"
    ],
    "entity": false,
    "pathRe": {
      "source": "^\\/(?:[a-z]{2}(?:-[a-z]{2})?\\/)?[^/?]+-l\\d+\\/[^/?]+-t\\d+\\/?(?:\\?.*)?$",
      "flags": ""
    },
    "selector": "#sticky-booking-assistant-configurator > .header > .badge-wrapper:not(:has(button, a, input, select, textarea, [role=\"button\"]))",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "^Likely to sell out$",
          "flags": ""
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 1523211246,
    "hosts": [
      "www.getyourguide.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "span.c-marketplace-badge--primary:not(:has(button, a, input, select, textarea, [role=\"button\"]))",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "^Likely to sell out$",
          "flags": ""
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 2282359013,
    "hosts": [
      "amazon.in",
      "www.amazon.in"
    ],
    "entity": false,
    "pathRe": null,
    "selector": ".a-carousel-card",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "cashback",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 3499420505,
    "hosts": [
      "amazon.in",
      "www.amazon.in"
    ],
    "entity": false,
    "pathRe": null,
    "selector": ".a-carousel-card",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "orders above",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 2587038438,
    "hosts": [
      "amazon.in",
      "www.amazon.in"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "a[href*=\"/alm/storefront\"]",
    "procedural": [
      {
        "type": "upward",
        "steps": ".a-carousel-card"
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 2023833575,
    "hosts": [
      "amazon-en"
    ],
    "entity": false,
    "pathRe": null,
    "selector": ".a-badge",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "limited time deal",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 4135333337,
    "hosts": [
      "amazon-en"
    ],
    "entity": false,
    "pathRe": null,
    "selector": ".a-badge",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "ends in",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 589668192,
    "hosts": [
      "www.booking.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "li.bui-list__item.bui-text--color-destructive-dark",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "we have \\d+ left",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 2521944857,
    "hosts": [
      "www.booking.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "[data-testid=\"recommended-units\"] div",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "^\\s*We have \\d+ left at this price\\s*$",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 1545353599,
    "hosts": [
      "www.agoda.com",
      "www.agoda.co.in"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "h5",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "^Hurry!.*fully booked!",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 2684320632,
    "hosts": [
      "www.agoda.com",
      "www.agoda.co.in"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "p.kite-js-Typography",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "in high demand on your selected dates",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 1500119733,
    "hosts": [
      "www.agoda.com",
      "www.agoda.co.in"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "[data-testid=\"room-offer\"] span:not(:has(button, a, input, select, textarea, [role=\"button\"]))",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "^\\s*Last booked \\d+\\s+(?:minutes?|hours?|hrs?)\\s+ago\\s*$",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 1016508069,
    "hosts": [
      "www.agoda.com",
      "www.agoda.co.in"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "#roomGridContent span",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "^Limited availability$",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 736052258,
    "hosts": [
      "www.agoda.com",
      "www.agoda.co.in"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "#roomGridContent span",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "^Last \\d+ rooms!$",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 319608009,
    "hosts": [
      "www.expedia.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "div.uitk-text.uitk-type-end",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "we have \\d+ left at this price",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 3273635184,
    "hosts": [
      "www.hotels.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "div.uitk-text.uitk-type-end",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "we have \\d+ left at this price",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 3619565006,
    "hosts": [
      "in.hotels.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "div.uitk-text.uitk-type-end",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "we have \\d+ left at this price",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 3568715519,
    "hosts": [
      "www.travelocity.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "div.uitk-text.uitk-type-end",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "we have \\d+ left at this price",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 912433863,
    "hosts": [
      "mloshoes.com",
      "www.mloshoes.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": ".announcement__slide",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "ends in",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 2945835325,
    "hosts": [
      "mloshoes.com",
      "www.mloshoes.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": ".badge-box.custom-box",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "best seller",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 1471857862,
    "hosts": [
      "us.shein.com",
      "www.shein.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "span.label-text",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "(\\d+k?\\+\\s+sold|user add to cart)",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 3041904213,
    "hosts": [
      "us.shein.com",
      "www.shein.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "span.nowrap-text",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "^(only \\d+ left!|almost sold out)",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 3101958043,
    "hosts": [
      "us.shein.com",
      "www.shein.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "span.incentive-text",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "almost sold out",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 974995192,
    "hosts": [
      "us.shein.com",
      "www.shein.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "span:has(.sui-icon-common__wrap)",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "almost sold out",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 3167120011,
    "hosts": [
      "euqs.shein.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "span.tags-text",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "(sold recently|returning customers|(sales|follower) surge)",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 760920002,
    "hosts": [
      "www.temu.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "span[class]",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "^\\s*(?:only\\s+\\d+\\s+left|\\d+(?:\\.\\d+)?[kK]?\\+?\\s*sold|limited stock|almost\\s+sold\\s+out!?|almost out!?|last day!?|ends\\s+in!?|\\d{1,2}:\\d{2}(?::\\d{2})?|#?\\d*\\s*(?:best-selling(?:\\s+brand)?\\s+item|top rated|most repurchased(?:\\s+brand)?\\s+item)(?:\\s*in\\s+.+)?|(?:\\d{1,2}\\s*:\\s*){1,5}\\d{1,2}(?:\\s+ends\\s+in!?)?)\\s*$",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 4209919575,
    "hosts": [
      "www.temu.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "div[class]",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "^\\s*(?:only\\s+\\d+\\s+left|\\d+(?:\\.\\d+)?[kK]?\\+?\\s*sold|limited stock|almost\\s+sold\\s+out!?|almost out!?|last day!?|ends\\s+in!?|\\d{1,2}:\\d{2}(?::\\d{2})?|#?\\d*\\s*(?:best-selling(?:\\s+brand)?\\s+item|top rated|most repurchased(?:\\s+brand)?\\s+item)(?:\\s*in\\s+.+)?|(?:\\d{1,2}\\s*:\\s*){1,5}\\d{1,2}(?:\\s+ends\\s+in!?)?)\\s*$",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 1679696372,
    "hosts": [
      "www.temu.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "span[data-type=\"0\"]",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "^\\s*(?:only\\s+\\d+\\s+left|\\d+(?:\\.\\d+)?[kK]?\\+?\\s*sold|limited stock|almost\\s+sold\\s+out!?|almost out!?|last day!?|ends\\s+in!?|\\d{1,2}:\\d{2}(?::\\d{2})?|#?\\d*\\s*(?:best-selling(?:\\s+brand)?\\s+item|top rated|most repurchased(?:\\s+brand)?\\s+item)(?:\\s*in\\s+.+)?|(?:\\d{1,2}\\s*:\\s*){1,5}\\d{1,2}(?:\\s+ends\\s+in!?)?)\\s*$",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 3181095155,
    "hosts": [
      "www.temu.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "span[data-type=\"0\"]",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "^\\s*fastest delivery in \\d+ business days\\s*$",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  },
  {
    "list": "darklist",
    "ruleId": 948592060,
    "hosts": [
      "www.temu.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "span[data-type=\"0\"]",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "^\\s*add now!\\s*almost out!?\\s*$",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "replace-text",
      "text": "Add to cart"
    }
  },
  {
    "list": "darklist",
    "ruleId": 293264927,
    "hosts": [
      "www.temu.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "span[data-type=\"0\"]",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "^\\s*buy now!\\s*almost out!?\\s*$",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "replace-text",
      "text": "Buy now"
    }
  },
  {
    "list": "darklist",
    "ruleId": 3000919336,
    "hosts": [
      "www.temu.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "span[data-type=\"0\"]",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "^\\s*buy now!\\s*last\\s+\\d+!?\\s*$",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "replace-text",
      "text": "Buy now"
    }
  },
  {
    "list": "darklist",
    "ruleId": 452740258,
    "hosts": [
      "www.temu.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "span[data-type=\"0\"]",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "^\\s*add the last\\s+\\d+!?\\s*$",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "replace-text",
      "text": "Add to cart"
    }
  },
  {
    "list": "darklist",
    "ruleId": 771182869,
    "hosts": [
      "www.temu.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "span[role=\"button\"]",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "^\\s*add the last\\s+\\d+!?\\s*$",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "replace-text",
      "text": "Add to cart"
    }
  },
  {
    "list": "darklist",
    "ruleId": 236650852,
    "hosts": [
      "www.temu.com"
    ],
    "entity": false,
    "pathRe": null,
    "selector": "span[class]",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "^\\s*add the last\\s+\\d+!?\\s*$",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "replace-text",
      "text": "Add to cart"
    }
  },
  {
    "list": "darklist",
    "ruleId": 3263828354,
    "hosts": [
      "www.thredup.com"
    ],
    "entity": false,
    "pathRe": {
      "source": "^\\/product\\/",
      "flags": ""
    },
    "selector": "div.body-copy-sm:has(> img[alt=\"Flame\"])",
    "procedural": [
      {
        "type": "has-text",
        "needle": {
          "source": "this item is popular.*likely to sell soon",
          "flags": "i"
        }
      }
    ],
    "action": {
      "type": "hide"
    }
  }
] as const;

export function revivePackagedRules(): PackagedRule[] {
  return (SERIALIZED as unknown as Array<StoredCompiledProc & { list: PackagedList }>).map((row) => ({
    list: row.list,
    rule: reviveCompiledProc(row),
  }));
}
